[package]
name = "node-wasm"
version = "0.1.0"
authors = ["Mika Fischer <mika.fischer@zoopnet.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"
console_error_panic_hook = "0.1.6"